# Stop if nginx not enabled
- block:
    - name: "End Installation if nginx not enabled"
      debug:
        msg: "Ending Admin Console Installation - Please make sure nginx is installed and enabled."
    - meta: end_play
  when: not nginx_enabled

- name: Create admin directory
  file: path={{ item }}
        mode=0755
        owner=root
        group=root
        state=directory
  with_items:
    - "{{ admin_install_base }}"

- name: Install admin lib files
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - { src: 'adm_const.py.j2', dest: '{{ py3_dist_path }}/iiab/adm_const.py' }
    - { src: 'adm_lib.py', dest: '{{ py3_dist_path }}/iiab/adm_lib.py' }

# Duplicate iiab test for internet
- name: Test for Internet access ({{ iiab_download_url }}/heart-beat.txt)
  get_url:
    url: "{{ iiab_download_url }}/heart-beat.txt"
    dest: /tmp/heart-beat.txt
  ignore_errors: True
  register: internet_access_test

- name: Set internet_available if download succeeded and not disregard_network
  set_fact:
    internet_available: True
  when: not internet_access_test.failed

- name: Remove downloaded Internet test file /tmp/heart-beat.txt
  file:
    path: /tmp/heart-beat.txt
    state: absent

# For Osm Vector Maps
# If not enabled install empty files
# Otherwise run /usr/bin/iiab-update-map

- name: Copy Osm Vector Maps dummy files
  copy:
    src: map/vector-map-idx.json
    dest: "{{ doc_root }}/common/assets/vector-map-idx.json"
    owner: root
    group: root
    mode: 0644
    force: yes
  when: not osm_vector_maps_enabled

- name: Copy Osm Vector Maps dummy files
  copy:
    src: map/regions.json
    dest: "{{ iiab_etc_path }}/regions.json"
    owner: root
    group: root
    mode: 0644
    force: yes
  when: not osm_vector_maps_enabled

- name: Create a link to osm catalog in /common/assets
  file:
    src: "{{ iiab_etc_path }}/regions.json"
    dest: "{{ doc_root }}/common/assets/regions.json"
    state: link

- name: Add any MAPS that are installed to home/menu.json
  shell: /usr/bin/iiab-update-map
  when: osm_vector_maps_enabled
